import path from "path";

export interface MockupManifestEntry {
  globKey: string;
  importPath: string;
}

function comparePaths(left: string, right: string): number {
  if (left < right) return -1;
  if (left > right) return 1;
  return 0;
}

export function buildMockupManifestEntries(
  files: readonly string[],
): MockupManifestEntry[] {
  return [...files].sort(comparePaths).map((file) => ({
    globKey: `./${file.slice("src/".length)}`,
    importPath: path.posix.relative("src/.generated", file),
  }));
}

export function generateMockupManifestSource(
  components: readonly MockupManifestEntry[],
): string {
  const entries = components
    .map(
      (component) =>
        `  ${JSON.stringify(component.globKey)}: () => import(${JSON.stringify(component.importPath)})`,
    )
    .join(",\n");

  return [
    "// This file is auto-generated by mockupPreviewPlugin.ts.",
    "type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;",
    "export const modules: ModuleMap = {",
    entries,
    "};",
    "",
  ].join("\n");
}
