uploads = []
outputs = []

[[generated]]
id = "6nXvvqwnPPLMVjQI3gI_p"
uri = "file://artifacts/woofwatcher-mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "X_TDgi_Y4_LZdgS_rZbvk"
uri = "file://artifacts/woofwatcher/public/phoenix-hero.png"
type = "image"
title = "phoenix hero meadow"

[[generated]]
id = "m9WvwWXCiHV4ft9RFprmu"
uri = "file://artifacts/woofwatcher/public/phoenix-avatar.png"
type = "image"
title = "phoenix avatar portrait"
