import { PixelRatio, Platform, type ImageStyle } from "react-native";

export const pixelImageStyle =
  Platform.OS === "web"
    ? ({ imageRendering: "pixelated" } as unknown as ImageStyle)
    : undefined;

const smoothImageStyle =
  Platform.OS === "web"
    ? ({ imageRendering: "auto" } as unknown as ImageStyle)
    : undefined;

// Nearest-neighbor sampling is only correct when pixel art is drawn at or
// above its source resolution. On a downscale it drops art pixels unevenly,
// which reads as crunchy edges - and once the image animates (sprite strips,
// the breathing room background) the dropped rows change every frame and the
// art shimmers. This picks pixelated for genuine upscales and smooth
// filtering for downscales, measured in device pixels against the sharpest
// bundled density variant (@2x/@3x generated by
// scripts/upscale-pixel-sprites.sh; pass maxBundledScale 1 for art without
// density variants). Native platforms always bilinear-filter, so they return
// undefined and rely on the supersampled variants alone.
export function pixelArtSamplingStyle(
  displaySizePx: number,
  sourceLogicalPx: number,
  maxBundledScale: 1 | 2 | 3 = 3,
): ImageStyle | undefined {
  if (Platform.OS !== "web") return undefined;
  const dpr = PixelRatio.get();
  const servedScale = Math.min(maxBundledScale, Math.max(1, Math.ceil(dpr)));
  return displaySizePx * dpr >= sourceLogicalPx * servedScale
    ? pixelImageStyle
    : smoothImageStyle;
}

// react-native-web's ImageBackground leaves the inner <img> at its natural
// pixel size when the wrapper has no explicit width/height (minHeight-only
// stages), so the card clips a giant top-left corner of the art instead of
// scaling it. Every stage ImageBackground must include this in imageStyle so
// the art fills the card and crops from the center on web and native alike.
export const stageImageFill: ImageStyle = {
  width: "100%",
  height: "100%",
  resizeMode: "cover",
  // react-native-web drops the resizeMode style key on the inner <img>, so
  // the CSS object-fit has to be set directly for the web preview/exports.
  ...(Platform.OS === "web" ? ({ objectFit: "cover" } as unknown as ImageStyle) : null),
};
