// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/brand-directions/NeoRetro.tsx": () => import("../components/mockups/brand-directions/NeoRetro.tsx"),
  "./components/mockups/brand-directions/PremiumPlayful.tsx": () => import("../components/mockups/brand-directions/PremiumPlayful.tsx"),
  "./components/mockups/brand-directions/Storybook.tsx": () => import("../components/mockups/brand-directions/Storybook.tsx"),
  "./components/mockups/signin-explore/BedtimeRitual.tsx": () => import("../components/mockups/signin-explore/BedtimeRitual.tsx"),
  "./components/mockups/signin-explore/CompanionWelcome.tsx": () => import("../components/mockups/signin-explore/CompanionWelcome.tsx"),
  "./components/mockups/signin-explore/PackWaiting.tsx": () => import("../components/mockups/signin-explore/PackWaiting.tsx")
};
